package com.bettinghouse.api.architecture.validator.dto;

public enum ApiErrorCode {
    
    NOT_FOUND, PROFILE_NOT_FOUND, PASSWORDS_DONT_MATCH, LOGIN_ALREADY_INFORMED, EMAIL_ALREADY_INFORMED, 
    INCORRECT_LOGIN_OR_PASSWORD, SPORT_NOT_ON_DATABASE, COINS_MUST_BE_POSITIVE, UNAUTHORIZED,
    USER_ALREADY_VIP, NOT_ENOUGH_COINS, SPORT_ALREADY_EXIST, TEAM_NOT_SELECTED, TEAM_DOESNT_BELONG_TO_SPORT,
    EVENT_NOT_FOUND, EVENT_ALREADY_CLOSED
}
